wandb_version: 1

epochs:
  desc: null
  value: 5
total_iters:
  desc: null
  value: 40001
batch_size:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710740950.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
