#### general settings
name: 001_SFTMD_DEMO_x4_demo_DIV2K
use_tb_logger: true
model: sftmd
distortion: sr
scale: 4
gpu_ids: [6, 7]
kernel_size: 21
code_length: 10
sig_min: 0.2
sig_max: 4.0
sig: 2.6

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: /mnt/yjchai/SR_data/Flickr2K_train/HR/x4
    dataroot_LQ: ~

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 32
    GT_size: 256
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K
    mode: LQGTker
    dataroot_GT: /mnt/yjchai/SR_data/DIV2K_test/HR/x4
    dataroot_LQ: ~

#### network structures
network_G:
  which_model_G: SFTMD # SRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 4
  code_length: 10

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  T_period: [125000, 125000, 125000, 125000]
  restarts: [125000, 250000, 375000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e4

sftmd:
  gpu_ids: [6, 7]
  is_train: False
  scale: 4
  datasets:
    test:
      name: DIV2K
      mode: LQGTker
      phase: test
      dataroot_GT: /mnt/yjchai/SR_data/Flickr2K/HR/x4
      dataroot_LQ: /mnt/yjchai/SR_data/Flickr2K/HR/x4
      GT_size: 256
      LR_size: 64
      data_type: img
      color: RGB

  model: sftmd

  network_G:
    which_model_G: SFTMD
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 16
    upscale: 4
    code_length: 10

  path:
    results_root: /media/sdc/yjchai/IKC/results
    pretrain_model_G: /media/sdc/yjchai/IKC/experiments/001_SFTMD_DEMO_x4_start_DIV2K/models/latest_G.pth
    strict_load: True
