#### general settings
name: HIT_UAV_SRGAN
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]
is_train: True

#### datasets
datasets:
  train:
    name: hit_uav_train
    mode: LQGT
    dataroot_GT: hit-uav/images/train
    dataroot_LQ: hit-uav/images/train  # Will be downsampled in dataset
    use_shuffle: true
    n_workers: 4
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: hit_uav_val
    mode: LQGT
    dataroot_GT: hit-uav/images/val
    dataroot_LQ: hit-uav/images/val  # Will be downsampled in dataset

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: ~
  pretrain_model_D: ~
  strict_load: true
  resume_state: ~
  models: ./experiments/hit_uav_srgan

#### training settings
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR
  restarts: None
  restart_weights: None

  niter: 20000  # Reduced for faster training
  warmup_iter: -1
  lr_steps: [5000, 10000, 15000, 20000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 5e-2
  feature_criterion: l2
  feature_weight: 0.7
  gan_type: wgan-qc
  gan_weight: !!float 1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 42
  val_freq: 500

  WQC_KCoef: 1
  WQC_gamma: 0.40

  edge_type: sobel
  edge_weight: !!float 1e-2
  edge_enhance: true

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
