batch_size: 45
GT_size: 128
gpu_ids: None
is_train: True
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_G: Discriminatort_VGG_128
  in_nc: 3
  nf: 64
train:
  lr_G: !!float 1e-4
  
  pixel_criterion: l1
  pixel_weight: !!float 1e-2

  feature_criterion: l1
  feature_weight: 0.7

  total_epochs: 1000
  